#!/usr/bin/env bash
# Creates a dump of all sql databases
mysqldump -u root --password="$1" -A --events > backup.sql

# Create the filename for the compressed archive 
name_of_file=$(date +"%d-%m-%Y")

# Create the compressed archive
tar -czvf "$name_of_file".tar.gz backup.sql
