#!/usr/bin/env bash
# This script configures Nginx to listen on port 80 and ensures it is running.

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart Nginx to apply changes
sudo service nginx restart
