#!/usr/bin/env bash
# Does a lot

pidfile="/var/run/my_process.pid"
logfile="/tmp/my_process"

# Function to display "I am alive!" every 2 seconds
to_infinity() {
	while true; do
		echo "I am alive!" >> $logfile
		sleep 2
	done
}

case "$1" in
	start)
		echo "manage_my_process started"
		to_infinity &
		echo $! > "$pidfile"
	;;
	stop)
		kill -TERM $(cat "$pidfile")
		rm -f "$pidfile"
		echo "manage_my_process stopped"
	;;
	restart)
		kill -TERM $(cat "$pidfile")
		rm -f "$pidfile"
		echo "manage_my_process restarted"	
		to_infinity &
		echo $! > "$pidfile"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		exit 1
		;;
esac
