#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
apache_log_file="./apache-access.log"
if [ ! -f "$apache_log_file" ]; then
    echo "Apache log file not found: $apache_log_file"
    exit 1
fi
awk '{count[$1 " " $9]++} END {for (item in count) print count[item], item}' "$apache_log_file" | sort -nr
