#!/usr/bin/env bash
# Configures an Ubuntu server
cp /etc/hosts /etc/hosts.new
if grep -q "localhost" /etc/hosts.new; then
    sed -i 's/^.*localhost$/127.0.0.2\tlocalhost/' /etc/hosts.new
else
    echo -e "127.0.0.2\tlocalhost" >> /etc/hosts.new
fi

if grep -q "facebook.com" /etc/hosts.new; then
    sed -i 's/^.*facebook.com$/8.8.8.8\tfacebook.com/' /etc/hosts.new
else
    echo -e "8.8.8.8\tfacebook.com" >> /etc/hosts.new
fi

cp /etc/hosts.new /etc/hosts
