#!/usr/bin/env bash
# Fix my server with these magic lines

# Start Apache service if not running
sudo service apache2 start

# Ensure the correct page is served
echo "Hello Holberton" | sudo tee /var/www/html/index.html

# Restart Apache to apply changes
sudo service apache2 restart
