#!/usr/bin/env bash
# Find the master Gunicorn process
GUNICORN_MASTER_PID=$(pgrep -f "gunicorn: master")

# Check if the master PID was found
if [ -n "$GUNICORN_MASTER_PID" ]; then
    kill -HUP "$GUNICORN_MASTER_PID"
fi
