#!/usr/bin/env bash
# This script reloads all Gunicorn master processes gracefully by identifying the leader.
systemctl status gunicorn | grep -oE 'Main PID: [0-9]+' | cut -d ' ' -f3 | xargs kill -HUP
