#!/usr/bin/env bash
# Find the master process ID of Gunicorn
GUNICORN_PID=$(pgrep -f "gunicorn")

# Check if the Gunicorn master process was found
if [ -n "$GUNICORN_PID" ]; then
    kill -HUP "$GUNICORN_PID"
fi
